#!/bin/bash

action=$1
shift

function usage(){
  echo "  Navigate to JIRA URL:"
  echo "    jira ITEM#"
  echo "      Launches a browser with https://issues.liferay.com/browse/ + first string in the task"
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

if ! [[ "$1" =~ ^[0-9]+$ ]]; then
    echo "Error! Usage:"
    usage
fi

URL=https://issues.liferay.com/browse/$(sed "$1!d" "$TODO_FILE"|grep -oP "(\(.\) )? *\K.*")
if [ "$URL" = "" ]; then
    echo "Error, no item #$1 found!"
    exit 1
fi

# Trying to be smart...
# with freedesktop.org utils:
if $(which xdg-open >/dev/null 2>&1); then
    exec xdg-open "$URL"
# on Debian alike:
elif $(which x-www-browser >/dev/null 2>&1); then
    exec x-www-browser "$URL"
# if you have git:
elif [ -x /usr/lib/git-core/git-web--browse ]; then
    cd /usr/lib/git-core && ./git-web--browse "$URL"
# last resort, a la mano...
elif $(which firefox >/dev/null 2>&1); then
    exec firefox "$URL"
elif $(which konqueror >/dev/null 2>&1); then
    exec konqueror "$URL"
elif $(which nautilus >/dev/null 2>&1); then
    exec nautilus "$URL"
# Windowsien?
elif [ -x "/cygdrive/c/Program Files/Mozilla Firefox/firefox.exe" ]; then
    exec "/cygdrive/c/Program Files/Mozilla Firefox/firefox.exe" "$URL"
# OS X?
elif [ -x "/usr/bin/open" ]; then
    exec "/usr/bin/open" "$URL"
else
    echo "Sorry I'm giving up, cannot find your browser :-("
    echo "Under cygwin, consider creating a shortcut in the path, like"
    echo "ln -s \"/cygdrive/c/Program Files/Mozilla Firefox/firefox.exe\" /usr/local/bin/firefox"
fi
